name: test
on:
  push:

env:
  HasConfigFile: false

jobs:
  action-1:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Check for config file in repo
        run: |
          echo "Checking for config file"
          ls -la ../../..
          ls -la ../../_temp
          ls -la ../../_PipelineMapping/FreelanceProjects-2-0
          if [[ -f .gitignore ]]
          then
                  echo "Config file exists"
                  HasConfigFile=true
          else
                  echo "Config file does not exist"
                  HasConfigFile=false
          fi
          echo "Test : $HasConfigFile"
